name: 📦 Build & Push Docker image

on:
  push:
    branches:
      - main # or your chosen branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Free up Docker space
      - name: Free up Docker space
        run: |
          docker system prune --all --volumes --force
          docker builder prune --all --force

      # 5. Build & push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/aidevgen-lipsync:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/aidevgen-lipsync:${{ github.sha }}
