name: 📦 Build & Push Docker image

on:
  push:
    branches:
      - main # or your chosen branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Clean up runner space before starting the job
      - name: Free up disk space
        run: |
          # Remove unnecessary packages and tool caches
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc \
            /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
            "$AGENT_TOOLSDIRECTORY" || true

          # Remove Docker images from previous runs
          docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true

          # Prune Docker system and volumes
          docker system prune --all --volumes --force
          docker builder prune --all --force

          # Clean apt cache and uninstall unnecessary software
          sudo apt clean
          sudo apt -y autoremove

          # Show available space after cleanup
          echo "Available disk space after cleanup:"
          df -h /

      # 2. Check out repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build & push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/aidevgen-lipsync:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/aidevgen-lipsync:${{ github.sha }}
          # Cache to improve build speeds
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 6. Cleanup after build to ensure space for future jobs
      - name: Post-build cleanup
        if: always()
        run: |
          # Clean up any build artifacts
          docker system prune --all --volumes --force
          docker builder prune --all --force

          # Show available space after all operations
          echo "Final available disk space:"
          df -h /
